export const TOGGLE_THEME = "TOGGLE_THEME";
export const SET_LOADING = "SET_LOADING";
export const GET_COUNTRIES = "GET_COUNTRIES";
export const FILTER_COUNTRIES = "FILTER_COUNTRIES";
export const COUNTRY_ERROR = "COUNTRY_ERROR";
